version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "mongo",
    "jest",
    "cypress",
    "mocha",
    "jquery",
    "browser"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"